# Generated by Django 4.2.30
# Renumbered to 0123 during the rebase onto upstream preview: upstream added its
# own 0122, and two migrations depending on 0121 is a branched history Django
# refuses to load.

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add the Webhook.page event subscription flag."""

    dependencies = [
        ("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="page",
            field=models.BooleanField(default=False),
        ),
    ]
